version: "3.9"

services:
  db:
    container_name: mcpod2_postgres
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./data:/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5431:5432

  backend:
    container_name: mcpod2_backend
    build: ./backend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db
    volumes:
      - ./data:/data
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PATH_TO_DATA_DIR: /data # must be the same as volumes container path

  frontend:
    container_name: mcpod2_frontend
    build: ./frontend
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./data/public:/var/www/public
    depends_on:
      - backend

volumes:
  postgres_volume:
